### ISSUE TITLE
how do you override the declaration order with stylelint-config-idiomatic-order?

### ISSUE THREAD

**Issue by catalin560** [bjankord/stylelint-config-sass-guidelines#110]
so I got a `.stylelintrc.json` that looks like:
```
{
    "extends": "stylelint-config-sass-guidelines",
    "rules": {
        "indentation": 4
    }
}
```
but I'd like to use the `stylelint-config-idiomatic-order` instead of the alphabetical one that seems to come with this plugin.
https://github.com/ream88/stylelint-config-idiomatic-order

**Comment by bjankord** [comment]
Try the following stylelint config setup:

```
module.exports = {
  extends: ['stylelint-config-sass-guidelines', 'stylelint-config-idiomatic-order'],
  rules: {
    "order/properties-alphabetical-order": null,
  },
};
```

This should disable the alphabetical sort order rule and user the property order rule from stylelint-config-idiomatic-order
