### ISSUE TITLE
calc w/ scss variable - no error

### ISSUE THREAD

**Issue by ELI7VH** [bjankord/stylelint-config-sass-guidelines#163]
given the following code:

```scss
height: calc(100% - $some-variable); 
```

the linter should return an error, because it is invalid.

**Comment by bjankord** [comment]
I'm open to a PR for a fix

**Comment by ELI7VH** [comment]
I would love to, I just don't know the first thing about how this works. Figured you might have a quick fix given you have the domain knowledge. 

Anyways. Just wanted to point it out. Thanks!

**Comment by binyamin** [comment]
@ELI7VH why is this invalid? The variable would just be replaced by the value of the variable, and the CSS would be valid.

**Comment by ELI7VH** [comment]
@binyamin I did a bit more research, and it looks like you have to interpolate the variable. would look like this in the end:

```
height: calc(100% - #{$some-variable}); 
```
https://stackoverflow.com/a/20236515
