### ISSUE TITLE
disable /  change property order

### ISSUE THREAD

**Issue by silveltman** [bjankord/stylelint-config-sass-guidelines#169]
I would like to disable or change the order of properties, but can't figure out how. The link to the 'declaration-block-properties-order' does not work.

I tried this to disable, neither works:
`  rules: {
    'declaration-block-properties-order': null,
    'properties-alphabetical-order': null,
  }`

Being able to change the order form alphabetic to idiomatic would also be ok. 

would love to get some help with this!

**Comment by bjankord** [comment]
Check this out and let me know if it works for you: https://github.com/bjankord/stylelint-config-sass-guidelines/issues/110#issuecomment-777498519

**Comment by robsonsobral** [comment]
No, it didn't. 😢
