### ISSUE TITLE
PostCSS Upgrade

### ISSUE THREAD

**Issue by shamikulamin** [bjankord/stylelint-config-sass-guidelines#175]
Hello it seems like today a security vulnerability for PostCSS v7 has been discovered and it looks like it has been resolved in v8.2.10.  Is there any plans to update the dependency to a safe version?

![Screen Shot 2021-05-10 at 4 43 14 PM](https://user-images.githubusercontent.com/8070989/117722541-30242380-b1af-11eb-85d9-6c020b27bc54.png)

**Comment by bjankord** [comment]
The issue is in a transitive dependency. I need to wait for postcss-sorting to consume the security patch from postcss, and then I need to wait for stylelint-order to consume the security patch of postcss-sorting and cut a release so I can consume that.

**Comment by bjankord** [comment]
PostCSS v7 was released with back-port of ReDoS fix. So stylelint users on current version of stylelint should see warning go away after running npm audit fix (it could take few days until npm audit will know about the fix).

https://twitter.com/PostCSS/status/1403351574110511106

**Comment by bjankord** [comment]
This should be resolved in v8.0.0 and the soon to be released v9.0.0 versions of this project.
