### ISSUE TITLE
Update scss/at-mixin-pattern

### ISSUE THREAD

**Issue by Schascha** [bjankord/stylelint-config-sass-guidelines#181]
Hello,

https://github.com/bjankord/stylelint-config-sass-guidelines/blob/ffa15c4106cbd75ea09327f4e8e10cc0be1379e6/index.js#L85

maybe prefer this regex:

`"scss/at-mixin-pattern": "^[a-z]+(-?[a-z0-9]+)+$"`

With that way mixins like `h1()` are possible and we can prevent mixins with multiple `-` like `foo--bar()`.

Thanks

**Comment by kerryj89** [comment]
I feel like with the popularity of BEM maybe double hyphens shouldn't be prevented by default `^[a-z]+(-{1,2}[a-z0-9]+)?`, but I guess the pattern starts to look too opinionated.

**Comment by bjankord** [comment]
I'm open to updating this.

**Comment by bjankord** [comment]
Thinking about this, I don't feel strongly about enforcing a strict regex for mixins. Planning to remove the scss/at-mixin-pattern rule in the next major (v10) release and then people can decide however they want to write their mixins.
