### ISSUE TITLE
Suggestion: Allow default scss/dollar-variable-pattern to match variables like $x1

### ISSUE THREAD

**Issue by kerryj89** [bjankord/stylelint-config-sass-guidelines#191]
My sass math functions had variables like `$x1` and `$y1`, so I updated the pattern to be: `^[a-z][0-9]?(-*[a-z0-9]+)*$`.  Is there some sass convention that says variables can't be one letter or a letter paired with a number that you often see in loops or math?

**Comment by bjankord** [comment]
I'm open to updating this.
