### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by williamjallen** [bjankord/stylelint-config-sass-guidelines#194]
It appears that the top link in [this](declaration-block-properties-order) section of the readme is broken.

**Comment by bjankord** [comment]
Thanks for raising the issue @williamjallen 
I found the following links no longer display the expected doc:
* https://stylelint.io/user-guide/rules/declaration-block-properties-order/
* https://stylelint.io/user-guide/rules/no-missing-eof-newline/ 
* https://stylelint.io/user-guide/rules/rule-nested-empty-line-before/ 
* https://stylelint.io/user-guide/rules/rule-non-nested-empty-line-before/
* https://stylelint.io/user-guide/rules/selector-no-id/
* https://stylelint.io/user-guide/rules/stylelint-disable-reason/

I link to all of these from this project's README.md file so I need to check and see what the team that maintains stylelint did with those pages.

**Comment by bjankord** [comment]
I went through and updated all the links to the stylelint rules documentation pages in the readme in this commit: https://github.com/bjankord/stylelint-config-sass-guidelines/commit/b07865bee9603cb49d86b834c4e3f221f6b80e6f
