### ISSUE TITLE
selector-class-pattern is not hyphenated_BEM

### ISSUE THREAD

**Issue by marcoturi** [bjankord/stylelint-config-sass-guidelines#20]
selector-class-pattern differs from the original rule of sass guidelines:
https://github.com/HugoGiraudel/sass-boilerplate/blob/master/.scss-lint.yml#L140

**Comment by bjankord** [comment]
Hi @marcoturi, thanks for the comment. I'm gonna keep the selector-class-pattern as hyphenated_lowercase for 2 reasons.

While I like BEM and think its a really good naming convention, I want the selector class pattern to be the most general / common way people write classes for this linter config. If you want to use a selector class pattern which follows BEM, you could extend this config and then overwrite the selector class pattern rule.

I do this in a project where we use the [SUIT naming convention](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md) for class patterns.

```
{
  "extends": "stylelint-config-sass-guidelines",
  "rules": {
    "selector-class-pattern": [
      "^ns-(?:[A-Z][a-zA-Z0-9]+)*(?:-[a-z0-9][a-zA-Z0-9]+)*?(?:--[a-z0-9][a-zA-Z0-9-]+)*?$|^(?:ns-)?(?:u|is|has|js)(?:-[a-z0-9][a-zA-Z0-9-]*)+$",
      {
        "message": "Class names should match the SUIT CSS naming convention"
      }
    ]
  }
}
```

The other reason I'm planning to keep it as is is that the [sass-guidelines website documentation](https://sass-guidelin.es/#scss-lint) shows hyphenated_lowcase as the class convention.
<img width="1009" alt="screen shot 2017-12-07 at 6 34 18 am" src="https://user-images.githubusercontent.com/633148/33715639-dedfb702-db18-11e7-9ed0-f3baf6eea7b6.png">

Though, if the hyphenated_lowercase which comes with this linter config doesn't work for your use-case, feel free to override the rule with whatever selector class pattern you want.

**Comment by marcoturi** [comment]
@bjankord Thank you for your fast response. I will try to find a regex that works for hyphenated_BEM and post it here.

**Comment by marcoturi** [comment]
Here it is: 
`"selector-class-pattern":"^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$"`

**Comment by polRk** [comment]
```typescript
"^[A-Z][a-z]*(?:\-[A-Z][a-z]*)?(?:\_[a-z]*)?(?:\_[a-z]*)?$"
```
