### ISSUE TITLE
Could not find "stylelint-order"

### ISSUE THREAD

**Issue by woodyrew** [bjankord/stylelint-config-sass-guidelines#22]
I get the following error when I enable `stylelint-config-sass-guidelines` in `.stylelintrc` from `stylelint` CLI _and_ Atom.
```
Error: Could not find "stylelint-order". Do you need a `configBasedir`?
```

![Could not find "stylelint-order". Do you need a `configBasedir`?](https://user-images.githubusercontent.com/1902064/35627861-21867574-0692-11e8-9a98-cff2bbe3a1f5.png)

Is there a solution?

**Comment by webmarkelov** [comment]
You need to add [plugins](https://github.com/bjankord/stylelint-config-sass-guidelines#plugins) for stylelint-config-sass-guidelines
```
npm i stylelint-order stylelint-scss -D
```

**Comment by AlesMenzel** [comment]
You need all dependencies that are listed in package.json under peerDependencies in satisfying versions.

`npm info "stylelint-config-sass-guidelines@latest" peerDependencies`
Currently that is:
```
"peerDependencies": {
    "stylelint": ">=8.0.0",
    "stylelint-order": ">=0.7.0",
    "stylelint-scss": ">=2.0.0"
},
```

```
npm i --save-dev stylelint@>=8.0.0 stylelint-order@>=0.7.0 stylelint-scss@>=2.0.0
```

This should be added to the readme as at first look it seems to be "battery included".

**Comment by bjankord** [comment]
I'm open to a PR if someone wants to update the README file noting the peer dependencies needed to be installed for this project.

**Comment by woodyrew** [comment]
Could `stylelint-order` be added to the `stylelint-scss` dependencies to avoid this?

**Comment by bjankord** [comment]
@woodyrew Yeah I'm fine adding `stylelint-order` and `stylelint-scss` to the dependencies.
