### ISSUE TITLE
Add "ignore" options to "max-nesting-depth" rule

### ISSUE THREAD

**Issue by stormwarning** [bjankord/stylelint-config-sass-guidelines#25]
It would be nice to not have nested at-rules count against the nesting-depth count. Updating the `max-nesting-depth` rule with the [available secondary rules](https://stylelint.io/user-guide/rules/max-nesting-depth/#optional-secondary-options) would allow this.

I can submit a PR for this in a bit.

**Comment by bjankord** [comment]
Cool, yeah, I'd be open to a pr for this.

**Comment by bjankord** [comment]
@stormwarning This is now available in v4.2.0: https://www.npmjs.com/package/stylelint-config-sass-guidelines
