### ISSUE TITLE
Suggestion: enable `scss/no-global-function-names`

### ISSUE THREAD

**Issue by Cedric-ruiu** [bjankord/stylelint-config-sass-guidelines#268]
Hi

Due to https://github.com/sass/sass/blob/main/accepted/module-system.md#built-in-modules-1, I think it's important to enable the rule `scss/no-global-function-names` from [stylelint-scss](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/no-global-function-names/README.md). I don't see any argument to leave it disabled. What do you think ?

**Comment by bjankord** [comment]
Yeah I'm open to a PR for enabling this.

**Comment by bjankord** [comment]
This has been added in v10.0.0

v10.0.0 is available now and supports stylelint v15: https://www.npmjs.com/package/stylelint-config-sass-guidelines/v/10.0.0
You can view the changelog here:  https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/CHANGELOG.md#1000
