### ISSUE TITLE
Update to Stylelint 15+

### ISSUE THREAD

**Issue by davidsneighbour** [bjankord/stylelint-config-sass-guidelines#272]
In the latest stylelint version a handfull of rules are deprecated and now throw warnings in current versions when running stylelint extending stylelint-config-sass-guidelines:

```
Deprecation warnings:
 - The "block-opening-brace-space-before" rule is deprecated.
 - The "color-hex-case" rule is deprecated.
 - The "declaration-bang-space-after" rule is deprecated.
 - The "declaration-bang-space-before" rule is deprecated.
...
```

Migration notes can be [found here](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md).

**Comment by FloEdelmann** [comment]
Allowing stylelint-config-sass-guidelines together with Stylelint v15 would be a good first step that could be released as a minor or patch version. See #273.

**Comment by bjankord** [comment]
v10.0.0 is available now and supports stylelint v15: https://www.npmjs.com/package/stylelint-config-sass-guidelines/v/10.0.0
You can view the changelog here:  https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/CHANGELOG.md#1000
