### ISSUE TITLE
Allow installing together with Stylelint v15

### ISSUE THREAD

**Issue by FloEdelmann** [bjankord/stylelint-config-sass-guidelines#273]
Stylelint v15 has deprecated many rules (see also #272), but all of them are still included. However, the strict peer dependency check in `npm` doesn't allow installing the latest `stylelint-config-sass-guidelines` with Stylelint v15:

```
$ npm install -D stylelint@15
npm ERR! While resolving: stylelint-config-sass-guidelines@9.0.1
npm ERR! Found: stylelint@15.2.0
npm ERR! node_modules/stylelint
npm ERR!   peer stylelint@">=14.0.0" from stylelint-config-html@1.1.0
npm ERR!   node_modules/stylelint-config-html
npm ERR!     dev stylelint-config-html@"^1.1.0" from the root project
npm ERR!   peer stylelint@"^14.5.1 || ^15.0.0" from stylelint-scss@4.4.0
npm ERR!   node_modules/stylelint-scss
npm ERR!     stylelint-scss@"^4.0.0" from stylelint-config-sass-guidelines@9.0.1
npm ERR!     node_modules/stylelint-config-sass-guidelines
npm ERR!       dev stylelint-config-sass-guidelines@"^9.0.1" from the root project
npm ERR!   2 more (the root project, stylelint-config-standard)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^14.0.1" from stylelint-config-sass-guidelines@9.0.1
npm ERR! node_modules/stylelint-config-sass-guidelines
npm ERR!   dev stylelint-config-sass-guidelines@"^9.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: stylelint@14.16.1
npm ERR! node_modules/stylelint
npm ERR!   peer stylelint@"^14.0.1" from stylelint-config-sass-guidelines@9.0.1
npm ERR!   node_modules/stylelint-config-sass-guidelines
npm ERR!     dev stylelint-config-sass-guidelines@"^9.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

To at least allow upgrading Stylelint to start using the new rules/fixes, and slowly migrate away from the deprecated rules, could the [peer dependency version](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/package.json#L39) be changed from `^14.0.1` to `^14.0.1 || ^15.0.0`?

This could be released as a minor or patch version, while removing deprecated rules like suggested in #272 would be a breaking change.

**Comment by echoix** [comment]
The megalinter project, https://GitHub.com/oxsecurity/megalinter that aggregates many linters is affected by this limitation. A npm install --force is used, but seems to break more things than it fixes. Could this be addressed soon ?

**Comment by AbdealiLoKo** [comment]
I seem to have the same issue, For some reason the `overrides` approach recommended by @rubiesonthesky does not work for me - On adding the to my package.json and using `npm i` still gives me the error.

**Comment by bjankord** [comment]
v10.0.0 is available now and supports stylelint v15: https://www.npmjs.com/package/stylelint-config-sass-guidelines/v/10.0.0
You can view the changelog here:  https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/CHANGELOG.md#1000

**Comment by echoix** [comment]
Great work! We'll work on reenabling this tool in the next Megalinter release!
