### ISSUE TITLE
Version 3.0.0 or 2.0.0 ?

### ISSUE THREAD

**Issue by tex0l** [bjankord/stylelint-config-sass-guidelines#4]
Hi,
Thanks for having updated your package, but obviously you released a 3.0.0 on npm, and your release tag is named v2.0.0 ;).

**Comment by bjankord** [comment]
Good question. I released v2.0.0 on GitHub and then ran a new [release script](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/package.json#L48) to publish the package to npm thinking it would follow the new v2.0.0 tag I just made. Instead, it bumped the project to v3.0.0 and released that version to npm... You live and your learn. 

I'm seeing if I can get v3.0.0 unpublished from the npm registry but not sure if that request will go through. I'll take a look at this again this evening and see if the v3.0.0 release is still on npm, if so, I plan to move forward with the v3.0.0 release.

**Comment by tex0l** [comment]
Thanks, it's no bother. I was only mindf****d to put ^2.0.0 and then have yarn telling me that no compatible version is available and letting me choose between 1.1.1 and 3.0.0 ^^.

**Comment by bjankord** [comment]
The v3.0.0 tag has been unpublished from npm. I plan to delete the current v3.0.0 tag/release on GitHub as well. I then plan to publish v2.0.0 to npm. 

A side effect of this is that the 3.0.0 tag can not be published to npm again. The next major release of this project after v2.0.0 will be 3.1.0 due to this.

**Comment by bjankord** [comment]
v2.0.0 is now available on npm. https://www.npmjs.com/package/stylelint-config-sass-guidelines
Sorry for the confusion.

**Comment by tex0l** [comment]
Thanks a lot!
