### ISSUE TITLE
Extending "stylelint-config-sass-guidelines" leads to fatal error

### ISSUE THREAD

**Issue by exophunk** [bjankord/stylelint-config-sass-guidelines#40]
As mentioned here: https://github.com/kristerkari/stylelint-scss/issues/266#issuecomment-433227160

One of the rules defined in your config creates stylelint to fatally crash due tue JS memory allocation:

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

It is all based on this rule:
https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/src/.stylelintrc.json#L90
`"scss/percent-placeholder-pattern": "^[a-z]+([a-z0-9-]+[a-z0-9]+)?$",`

I copied all your config directly into my `.stylelintrc` except this one rule and everything was fine.

Maybe you can fix it by just upgrading your dependencies of `stylelint-scss`

Thanks!

**Comment by bjankord** [comment]
From reading through the linked issue, it sounds like v5 of https://github.com/postcss/postcss-selector-parser may resolve it, just waiting for that to be released.

**Comment by bjankord** [comment]
https://github.com/postcss/postcss-selector-parser v5 has been [released](https://github.com/postcss/postcss-selector-parser/issues/166#issuecomment-444440963). This package is now pulled in to stylelint-config-sass-guidelines.

Let me know if this resolves the issue you are seeing.
