### ISSUE TITLE
Ignore all @-rules in max-nesting-depth

### ISSUE THREAD

**Issue by xi** [bjankord/stylelint-config-sass-guidelines#44]
#33 was an issue about ignoring `@each` in "max-nesting-depth". But what about `@if`, `@for`, `@while`, `@function`, …? The guidelines only talk about *selector nesting* so I see no reason not to ignore *all* @-rules.

**Comment by bjankord** [comment]
That is a good point, I'd be open to a PR to add to the [list of @ directives](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/src/.stylelintrc.json#L36) that are ignored by the max-nesting-depth rule.

**Comment by bjankord** [comment]
Thanks for the PR @xi 
This has been released in https://github.com/bjankord/stylelint-config-sass-guidelines/releases/tag/v5.4.0

**Comment by xi** [comment]
Thanks for the quick reply!
