### ISSUE TITLE
Disable declaration-block-properties-alphabetical-order

### ISSUE THREAD

**Issue by CrashyBang** [bjankord/stylelint-config-sass-guidelines#5]
Hey is it possible to disable the `declaration-block-properties-alphabetical-order` I currently have:

```json
"order/declaration-block-properties-alphabetical-order": false
```

Which works but gives the following error:

```
Invalid Option: Unexpected option value "false" for rule "order/declaration-block-properties-alphabetical-order"
```

Was hoping there was a native way to do this?

Cheers.

**Comment by bjankord** [comment]
Hmm, here is the doc on this rule: https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-alphabetical-order/README.md

Not sure, but I think this may be an issue upstream in [stylelint-order](https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-alphabetical-order/README.md).

**Comment by bjankord** [comment]
Can you post your package.json file and your stylelint config?

**Comment by tristanbes** [comment]
it's `null` I think instead of false;

**Comment by CrashyBang** [comment]
Hey @tristanbes yes thank you. Sorry @bjankord only just saw your comment.
