### ISSUE TITLE
Stylelint v10

### ISSUE THREAD

**Issue by Arelav** [bjankord/stylelint-config-sass-guidelines#50]
Hello.
Stylelint v10 was released long time ago and I can't see any issues except getting the warinig:
`warning "stylelint-config-sass-guidelines > stylelint-scss@3.5.4" has incorrect peer dependency "stylelint@^8.0.0 || ^9.0.0".`

Could be the library dependency to be allowed also for ^10.0.0, please?

**Comment by bjankord** [comment]
The current version, v6, has [a peer dependency on stylelint ^10.0.1](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/package.json#L35)

The error you are seeing if from stylelint-scss@3.5.4, it has the [peerDependency on `stylelint@^8.0.0 || ^9.0.0`](https://github.com/kristerkari/stylelint-scss/blob/3.5.4/package.json#L47)

Its likely that your project has a lock file that is limiting stylelint-scss to 3.5.4. If you pull in the latest version of stylelint-scss, the error should go away.

**Comment by Arelav** [comment]
Thank you very much for so quick response.
It works.
