### ISSUE TITLE
Stylelint v13 support

### ISSUE THREAD

**Issue by gussyboy** [bjankord/stylelint-config-sass-guidelines#60]
Can you please add support for stylelint v13

**Comment by bjankord** [comment]
Waiting on [this PR](https://github.com/kristerkari/stylelint-scss/pull/428/files) to land and be released before I can roll this out.

**Comment by bjankord** [comment]
Merged down the PR with stylelint v13 support. I'll be working on a release.

**Comment by RiZKiT** [comment]
Good that the peer dependency warning will disappear with that, but was it intended to drop v10-v12? Stylelint v13 is just two weeks old.
