### ISSUE TITLE
Is vscode autofix supported? Getting error command 'stylelint.executeAutofix' not found

### ISSUE THREAD

**Issue by JackHowa** [bjankord/stylelint-config-sass-guidelines#71]
Was directed to check by the vs code extension here? https://github.com/stylelint/vscode-stylelint/issues/101

I'm curious if there's integration with stylelint vscode extension with sass guidelines.

Thanks so much for your work. This has really helped our codebase

**Comment by SharakPL** [comment]
I've just checked and everything seems to work fine. Do you have proper settings in VScode?
```
    "[scss]": {
        "editor.codeActionsOnSave": {
            "source.fixAll.stylelint": true
        },
    },
```

**Comment by JackHowa** [comment]
woah, yeah. working as expected. thank you, I was missing `"[scss]": {`. Appreciate it @SharakPL
