### ISSUE TITLE
What is the src/.scss-lint.yml file for?

### ISSUE THREAD

**Issue by iwis** [bjankord/stylelint-config-sass-guidelines#77]
What is the [src/.scss-lint.yml](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/src/.scss-lint.yml) file for? Does its content affect the way stylelint works? If yes, then how does its content relate to the rules defined in [src/.stylelintrc.json](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/src/.stylelintrc.json)?

I'm trying to understand _stylelint-config-sass-guidelines_ rules, and I wonder if there are any other rules in addition to rules defined in src/.stylelintrc.json.

**Comment by iwis** [comment]
By running the `npx stylelint . --print-config` command I have checked that the following configs are identical:

a)
```
{
  "plugins": ["stylelint-scss", "stylelint-order"],
  "extends": ["stylelint-config-sass-guidelines"],
}
```


b)
```
{
  "plugins": ["stylelint-scss", "stylelint-order"],
  "rules": {
    << all rules from src/.stylelintrc.json >>
  }
}
```

So I believe that `src/.scss-lint.yml` file doesn't affect the way stylelint works.

**Comment by bjankord** [comment]
You are correct, `src/.scss-lint.yml` is not used in relation to stylelint. That file contains the scss-lint rules used in Sass Guidelines and I've used to compare to rules used in stylelint:
https://github.com/bjankord/stylelint-config-sass-guidelines/wiki/Lint-Rule-Comparison
https://github.com/bjankord/stylelint-config-sass-guidelines/wiki/Lint-Report-Comparison
In regards to learning more about the guidelines, you can check out these comparisons ^

I may move that file out of the `src` directory so it is less confusing.
