### ISSUE TITLE
Declaration block properties order Rule

### ISSUE THREAD

**Issue by deerawan** [bjankord/stylelint-config-sass-guidelines#79]
Hi,

I found something to clarify
 
Regarding 
```
declaration-block-properties-order: Properties in declaration blocks must be sorted alphabetically.
```
Based on the page, the author didn't impose preference regarding property order 

![image](https://user-images.githubusercontent.com/1243921/83845125-9d336b80-a74b-11ea-845d-26eaa7e2ca31.png)

I wonder if it is better to remove the Rule to follow what the doc said? 

However, In the `.stylelint.rc` I could do this to ignore the rule

```json
{
"extends": "stylelint-config-sass-guidelines",
"rules": {
    "order/properties-alphabetical-order": null
  }
}
```

**Comment by bjankord** [comment]
That's a good point. When I created this, the team I worked on favored alpha ordering so thats what I went with. If you find that you either don't prefer this ordering or want another option for ordering, I think the rule override is a good option.
