### ISSUE TITLE
Is this compatible with stylelint-config-standard?

### ISSUE THREAD

**Issue by danrneal** [bjankord/stylelint-config-sass-guidelines#95]
Am I able to use both configs as such:

```
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-sass-guidelines"
  ]
}
```

And if so, which should come first?
If this is the case, it might be useful information for the README, I'd be willing to PR it.

**Comment by bjankord** [comment]
I'm not sure. If you try it out let me know, I would recommend extending it how you have in your comment and see how it goes.
